import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { getClerkPublishableKey, getPrymeiraHubUrl } from "./runtime-config";

describe("runtime config", () => {
  it("prefers the runtime Clerk publishable key over the Vite build-time key", () => {
    expect(getClerkPublishableKey({
      viteEnv: { VITE_CLERK_PUBLISHABLE_KEY: "pk_build" },
      runtimeConfig: { clerkPublishableKey: "pk_runtime" }
    })).toBe("pk_runtime");
  });

  it("falls back to the Vite build-time Clerk publishable key", () => {
    expect(getClerkPublishableKey({
      viteEnv: { VITE_CLERK_PUBLISHABLE_KEY: "pk_build" },
      runtimeConfig: {}
    })).toBe("pk_build");
  });

  it("reads the Prymeira runtime key generated by the container", () => {
    expect(getClerkPublishableKey({
      runtimeConfig: { VITE_CLERK_PUBLISHABLE_KEY: "pk_container" }
    })).toBe("pk_container");
  });

  it("ships a local config.js placeholder for Vite development", () => {
    const configPath = resolve(process.cwd(), "public/config.js");
    expect(existsSync(configPath)).toBe(true);

    const configSource = readFileSync(configPath, "utf8");
    const window = {} as { __PRYMEIRA_CONFIG__?: unknown };
    new Function("window", configSource)(window);

    expect(window.__PRYMEIRA_CONFIG__).toEqual({});
  });

  it("reads the Prymeira Hub URL from runtime config", () => {
    expect(getPrymeiraHubUrl({
      runtimeConfig: { VITE_PRYMEIRA_HUB_URL: "https://hub.prymeiradigital.com.br/" }
    })).toBe("https://hub.prymeiradigital.com.br");
  });
});
