import { describe, expect, it } from "vitest";
import { getClerkPublishableKey } from "./runtime-config";

describe("runtime config", () => {
  it("prefers the runtime Clerk publishable key over the Vite build-time key", () => {
    expect(getClerkPublishableKey({
      viteEnv: { VITE_CLERK_PUBLISHABLE_KEY: "pk_build" },
      runtimeConfig: { clerkPublishableKey: "pk_runtime" }
    })).toBe("pk_runtime");
  });

  it("falls back to the Vite build-time Clerk publishable key", () => {
    expect(getClerkPublishableKey({
      viteEnv: { VITE_CLERK_PUBLISHABLE_KEY: "pk_build" },
      runtimeConfig: {}
    })).toBe("pk_build");
  });

  it("reads the Prymeira runtime key generated by the container", () => {
    expect(getClerkPublishableKey({
      runtimeConfig: { VITE_CLERK_PUBLISHABLE_KEY: "pk_container" }
    })).toBe("pk_container");
  });
});
